
spring:
  application:
    name: grocery-checkout-boot3
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump
  endpoint:
    health:
      show-details: always

catalog:
  prices:
    BANANAS: 0.50
    ORANGES: 0.30
    APPLES: 0.60
    LEMONS: 0.25
    PEACHES: 0.75

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    display-request-duration: true
    doc-expansion: none
  api-docs:
    enabled: true
